class Food {
  String name;
  String description;
  String photo;
  String ingredient;
  String procedure;

  Food({
    required this.name,
    required this.description,
    required this.photo,
    required this.ingredient,
    required this.procedure
  });
}

var foodList = [
  Food(
      name: 'Gudeg',
      description: 'Gudeg adalah makanan khas Yogyakarta yang terbuat dari nangka muda (gori) yang direbus selama beberapa jam dengan gula kelapa serta santan hingga menghasilkan kuah (areh) yang kental. Rasanya yang manis dan legit menjadi ciri khas hidangan yang satu ini.\n\nDibutuhkan waktu beberapa jam untuk memasak gudeg hingga masak. Warna coklat biasanya dihasilkan dari daun jati. Popularitas tersebut juga yang membuat Yogyakarta dikenal dengan nama Kota Gudeg.\n\nGudeg biasa dilengkapi dengan nasi putih, ayam, telur rebus, tahu atau tempe, dan rebusan terbuat dari kulit sapi segar atau lebih dikenal dengan nama sambal goreng krecek. Pada penyajiannya, ada beberapa jenis gudeg yang dikenal saat ini yaitu jenis gudeg kering dan gudeg basah.',
      photo: 'images/gudeg.jpeg',
      ingredient: '- 1 kg nangka muda\n - 5 butir telur ayam rebus, kupas\n - 2 lembar daun salam\n - 3 lembar daun jeruk\n - 3 cm lengkuas, memarkan\n - 120 g gula Jawa yang cokelat tua\n - 1.5 liter santan sedang\n - 500 ml santan kental\n\nBumbu:\n - 8 butir bawang merah\n - 5 siung bawang putih\n - 5 butir kemiri\n - 1 sdm ketumbar\n - 1 potong terasi\n - 1/4 sdt jintan\n - 2 sdt garam\n\nPelengkap:\n - Sambal goreng krecek\n - Opor ayam\n - Sambal bajak\n',
      procedure: '1. Potong nangka muda berbentuk dadu besar. Rebus nangka muda dalam air atau air kelapa tua secukupnya hingga lunak. Angkat dan tiriskan nangka muda.\n2. Bumbu Halus: Haluskan semua bahan bumbu dengan blender atau ulekan hingga halus benar.\n3. Masukkan nangka muda dan telur ke dalam panci. Tuangi santan, masukkan bumbu halus, daun salam, daun jeruk, lengkuas dan gula merah.\n4. Masak dengan api sedang hingga bumbu meresap dan kuahnya susut.\n5. Tuangkan santan kental. Masak dengan api hingga kuah benar-benar susut. Matikan api.\n6. Sajikan gudeg dengan pelengkapnya.\n'
  ),
  Food(
      name: 'Bika Ambon',
      description: 'Bika ambon adalah sejenis jajanan manis yang berasal dari Sumatera Utara. Makanan ini berwarna kuning dengan tekstur yang legit, tetapi berlubang-lubang. Kue tersebut menggunakan tepung sagu sebagai bahan dasarnya.\n\nBika ambon terbuat dari bahan-bahan seperti tepung sagu, gula, susu, santan, daun pandan, serai, dan daun jeruk. Bika ambon cocok dimakan sebagai teman minum teh dengan aroma yang harum sekali dan rasanya lembut.\n\nRasa bika ambon yang manis dan legit memang banyak sekali disukai, apalagi sekarang varian rasa bika ambon juga semakin berkembang seperti durian, keju, coklat, dan lainnya.',
      photo: 'images/bika.jpeg',
      ingredient: '- Kuning telur - 12 butir\n - Gula pasir - 150 gram\n - Tepung sagu - 100 gram\n - Santan kental - 200 ml\n - Daun jeruk - 10 lembar\n - Serai, ambil bagian putihnya lalu memarkan - 1 batang\n - Garam - 1/4 sdt\n\nBIANG:\n - Ragi instan - 1 sdt\n - Gula pasir - 1 sdm\n - Terigu - 1 sdm\n - Air hangat - 50 ml\n',
      procedure: ' 1. Dalam wadah, campurkan semua bahan biang hingga rata. Diamkan selama 15 menit. Sisihkan.\n2. Dalam panci, rebus santan bersama daun jeruk, serai, dan garam dengan api kecil sampai mendidih. Angkat lalu diamkan hingga suhunya turun. Sisihkan.\n3. Kocok kuning telur dan gula hingga gula larut.\n4. Masukkan tepung sagu dan hasil rebusan santan tadi secara bergantian. Aduk rata.\n5. Masukkan bahan biang. Aduk hingga rata. Diamkan selama minimal 2 jam.\n6. Tuang adonan ke dalam loyang yang sudah dipanaskan. Hentakkan loyang perlahan agar adonan rata.\n7. Masukkan oven dan panggang selama 40 menit dengan suhu 180°C. Biarkan oven sedikit terbuka selama 30 menit pertama atau sampai kue terlihat bergelembung dan berlubang-lubang. Baru selebihnya tutup rapat oven. Keluarkan kue.\n8. Siap disajikan.\n'
  ),
  Food(
      name: 'Rendang',
      description: 'Rendang adalah salah satu warisan kuliner dari daerah Sumatera Barat. Terbuat dari daging sapi yang dimasak dengan bumbu rempah lengkap, rasa rendang mampu memukau penikmat kuliner dari seluruh penjuru tanah air dan bahkan hingga ke luar negeri.\n\nRasa rendang sangat enak dan kaya bumbu. Masakan ini dihasilkan dari proses memasak yang dipanaskan berulang-ulang dengan santan kelapa. Proses memasaknya sekitar empat jam hingga kering dan berwarna coklat pekat.\n\nDi daerah Minangkabau, rendang disajikan dalam berbagai upacara adat dan perhelatan istimewa. Rendang dapat ditemukan di rumah makan padang di seluruh Indonesia dan sudah terkenal di mancanegara.\n\nPada tahun 2011, rendang dinobatkan sebagai hidangan peringkat pertama daftar World\'s 50 Most Delicious Food (50 Hidangan Terlezat Dunia) yang digelar oleh CNN International.',
      photo: 'images/rendang.jpeg',
      ingredient: '- 1 kg daging sapi\n - 3 butir kelapa, diambil santan kental dan santan encernya\n - 4 lembar daun jeruk\n - 3 batang serai, memarkan\n - 4 butir asam kandis\n - 100 ml minyak goreng\n - 5 gram garam\n - Bumbu rendang daging sapi 1 Kg\n - 60 gram bawang merah\n - 50 gram bawang putih\n - 250 gram cabai merah besar\n - 100 gram lengkuas\n - 50 gram kemiri\n - 2 gram cengkeh\n',
      procedure: '1. Haluskan semua bahan Bumbu dengan diulek atau diblender.\n2. Tumis bumbu dengan sedikit minyak goreng hingga wangi.\n3. Masukkan batang serai, daun jeruk, asam kandis dan garam, aduk rata.\n4. Tuangi santan dan dididihkan, masukkan daging.\n5. Masak dengan api kecil selama beberapa jam sampai daging empuk dan bumbu kecokelatan sesuai selera.\n'
  ),
  Food(
      name: 'Pempek',
      description: 'Pempek atau empek-empek adalah makanan khas yang berasal dari Sumatera Selatan. Pempek palembang terbuat dari ikan dan tepung sagu. Makanan ini banyak digemari karena rasanya yang gurih dan kuah (cuko)nya yang pedas, asam, dan manis.\n\nCuko berwarna hitam kecoklat-coklatan terbuat dari air yang dididihkan, kemudian ditambah gula merah, udang ebi, cabe rawit tumbuk, bawang putih, dan garam. Pelengkap dalam menyantap makanan berasa khas ini adalah irisan dadu timun segar dan mie kuning.',
      photo: 'images/pempek.jpeg',
      ingredient: '- 500 gram ikan tenggiri\n - 300 gram air\n - 5 gram gula pasir\n - 25 gram garam\n - 5 gram penyedap rasa\n - 350 gram tepung sagu\n',
      procedure: ' 1. Campur rata ikan tenggiri halus dan air menggunakan tangan.\n2. Masukkan gula pasir, garam, dan penyedap rasa. Campur rata sampai adonan agak mengental. Masukkan tepung sagu ke dalam adonan. Campur perlahan menggunakan tangan, jangan diaduk terlalu keras.\n3. Bagi adonan menjadi masing-masing 150 gram untuk lenjer besar atau 25 gram untuk lenjer kecil. Bentuk seperti silinder.\n4. Rebus pempek dengan api sedang sampai mengapung dan permukaannya licin. Angkat dan tiriskan. Sajikan pempek dengan cuko.\n'
  ),
  Food(
      name: 'Kerak Telor',
      description: 'Kerak telor merupakan makanan khas berupa jajanan yang berasal dari Jakarta atau Betawi. Kerak telor terbuat dari beras ketan putih, telur bebek, ebi (udang kering yang diasinkan) yang disangrai kering ditambah bawang merah goreng, lalu diberi bumbu yang dihaluskan.\n\nBumbu tersebut berupa kelapa sangrai, cabai merah, kencur, jahe, merica butiran, garam, dan gula pasir. Kerak telor rasanya gurih karena terdapat bawang goreng dan telur, sedikit manis karena ada serundeng, dan mengenyangkan karena bahan dasarnya berupa beras ketan. Kerak telor banyak dijumpai di acara kebudayaan Betawi.',
      photo: 'images/keraktelor.jpeg',
      ingredient: ' - 6 sdm beras ketan, rendam semalam dan tiriskan\n- 2 buah telur bebek\n- 2 sdt udang kering, rendam, sangrai dan haluskan\n- 2 sdm kelapa parut setengah tua, sangria\n- 1 sdm bawang goreng\n\nBumbu lain\n- 1 sdm cabai merah iris, sangria dan haluskan\n- 1 sdt garam\n- 1 sdm cabai bubuk (opsional)\n',
      procedure: '1. Pertama, kocok telur bebek. Kemudian masukkan udang kering, bumbu yang dihaluskan, bawang goreng, dan kelapa sangrai. Aduk rata.\n2. Panaskan wajan dadar anti lengket atau teflon. Tuang setengah bagian ketan. Ratakan di permukaan wajan. Masak hingga setengah matang.\n3. Tuang setengah bagian telur kocok berbumbu. Ratakan di seluruh permukaan sambil ditekan-tekan. Setelah bagian bawahnya matang, dapat dibalik agar matang merata.\n4. Hidangkan kerak telur selagi panas.\n5. Bila Sedulur menyukai kerak telur dengan cita rasa pedas, maka bisa menambahkan bubuk cabe di atas adonan kerak telur yang sudah matang.\n'
  ),
  Food(
      name: 'Lumpia Basah',
      description: 'Lumpia adalah makanan khas dari Semarang, Jawa Tengah. Makanan ini berupa lembaran tipis dari tepung gandum yang dijadikan kulit lalu digunakan sebagai pembungkus isian yang dapat berupa rebung, telur, sayuran segar, dan daging.\n\nMakanan ini sebenarnya berasal dari Tionghoa yang telah dimodifikasi sehingga bercita-rasa Indonesia. Lumpia dibuat dengan cara digoreng dan biasanya disajikan bersama saus bawang putih atau cabai.',
      photo: 'images/lumpia.jpeg',
      ingredient: 'Bahan kulit\n - 250 gram tepung terigu protein sedang\n - 1 sdt tepung tapioka\n - 1 butir telur 1/4 sdt garam\n - 400 ml air\n\nBumbu halus\n - 5 buah bawang putih\n - 1 sdt lada halus\n - 1/2 sdt garam\n - 1 sdt kaldu bubuk\n - 1 sdm saos tiram\n - 1 buah bengkoang, iris korek api\n - 1 buah tahu cina, iris dadu kecil, goreng\n - 100 gram taoge, buang ekornya\n - 1 buah wortel, serut, seduh dengan air panas\n - 1 batang daun bawang, rajang halus\n - 50 ml minyak goreng untuk menumis\n',
      procedure: '1. Campurkan tepung terigu, tepung tapioka, garam, aduk menjadi satu. Masukkan telur di tengah-tengah tepung, aduk dengan sendok atau balloon whisk. Tuang air sedikit demi sedikit hingga menjadi adonan cair.\n2. Siapkan teflon dan tuang adonan kulit lumpia basah. Sisihkan.\n3. Isi kulit lumpia basah: Panaskan minyak goreng, tumis bumbu halus hingga harum. Masukkan wortel dan bengkoang, aduk hingga layu.\n4. Masukkan taoge, tahu, dan daun bawang. Beri sedikit air bila perlu. Aduk hingga kering. Angkat dan taruh di piring.\n5. Ambil satu lembar kulit lumpia basah, beri sekitar satu sendok makan bahan isi, lipat seperti amplop. Lakukan hingga semua kulit lumpia habis. Sajikan lumpai basah bersama bawang lokio dan cabai rawit.\n'
  ),
  Food(
      name: 'Rujak Cingur',
      description: 'Rujak cingur merupakan makanan khas dari Jawa Timur. Kata cingur berarti mulut, mulut yang digunakan sebagai bahan baku utama ialah mulut sapi. Irisan cingur sapi yang telah direbus hingga lunak.\n\nRujak cingur biasanya terdiri dari irisan beberapa jenis buah-buahan seperti ketimun, mangga muda, bengkoang, nanas, kedondong, ditambah lontong, tempe, tahu, bendoyo, dan sayur-sayuran.\n\nBahan tadi dicampur dengan saus berwarna coklat kehitaman yang terbuat dari olahan petis udang, air matang, gula merah, kacang tanah goreng, bawang goreng, cabai, garam, dan irisan tipis-tipis pisang klutuk. Semua bahan saus tersebut dicampur dengan cara diuleg.',
      photo: 'images/rujak.jpg',
      ingredient: ' - Cingur - 250 gram\n- Tauge - 50 gram\n- Kangkung - 2 ikat\n- Mentimun - 1 buah\n- Bengkuang - 1 buah\n- Tempe - 1/2 papan\n- Tahu - 2 buah\n\nBUMBU RUJAK:\n- Cabai rawit (optional) - 8 buah\n - Kacang tanah goreng - 3 sdm\n - Petis udang - 2 sdm\n - Bawang putih goreng - 2 siung\n - Air asam jawa - 4 sdm\n - Gula merah, iris - 2 sdm\n - Garam - 1/4 sdt\n - Pisang klutuk / batu, parut kasar - 2 buah\n - Air matang - secukupnya\n\nPELENGKAP:\n - Lontong - secukupnya\n - Kerupuk - secukupnya\n - Bawang putih goreng - secukupnya\n',
      procedure: 'CARA MEMBUAT CINGUR\n1. Rebus cingur sampai empuk, tiriskan, kemudian potong-potong.\n2. Petik-petik daun kangkung lalu rebus sampai matang.\n3. Rendam tauge dengan air panas, tiriskan.\n4. Potong tipis mentimun dan bengkuang, sisihkan.\n5. Goreng tempe dan tahu sampai matang, kemudian potong-potong.\n\nCARA MEMBUAT BUMBU RUJAK\n1. Haluskan cabai rawit, kacang tanah, bawang putih, gula merah, garam, dan pisang klutuk.\n2. Tambahkan petis udang, air asam jawa dan air secukupnya, aduk rata.\n3. Tata sayuran, cingur, tahu dan tempe goreng di piring\n4. Siram dengan bumbu rujak.\n5. Sajikan dengan lontong, kerupuk serta bawang putih goreng.\n'
  ),
  Food(
      name: 'Lapa-Lapa',
      description: 'Lapa-lapa adalah makanan khas dari Sulawesi Tenggara. Makanan tersebut dibuat menggunakan beras bersama dengan santan, cukup dua bahan itu saja, namun untuk memenuhi persyaratan lapa-lapa maka diperlukan janur.\n\nLapa-lapa terbuat dari beras yang dimasak dengan santan sehingga rasanya sangat gurih. Pertama beras dimasak setengah matang kemudian baru dibungkus dengan daun kelapa. Selanjutnya lapa-lapa dikukus kembali. Makanan ini akan semakin nikmat jika dimakan bersama kaholeonarore (ikan asin).',
      photo: 'images/lapalapa.jpeg',
      ingredient: '  - 2 butir kelapa, diambil santan kentalnya\n - Secukupnya tali benang\n - 1 kg beras ketan putih\n - Secukupnya daun kelapa\n - Secukupnya garam\n',
      procedure: '1. Cuci beras ketan kemudian rendam di dalam air selama sekitar 2 jam\n2. Kukus beras ketan\n3. Sembari menunggu beras ketan matang, rebus santan kental sampai mendidih sambil terus diaduk-aduk biar santan tidak pecah. Tambahkan garam secukupnya biar makin gurih\n4. Jika beras ketan sudah matang, segera tuangkan santan kentalnya\n5. Bungkus dengan daun kelapa mudah dengan bentuk memanjang\n6. Ikat dengan benang hingga tertutup rapat\n7. Setelah itu, kukus lagi selama kurang lebih 1½ jam\n8. Angkat dan lapa-lapa sudah siap untuk dihidangkan\n'
  ),
  Food(
      name: 'Karedok',
      description: 'Karedok merupakan makanan khas dari Jawa Barat. Makanan ini didominasi oleh sayuran hijau. Di daerah Sunda, karedok kacang panjang sangat populer dengan rasa enak dan segar terlebih lagi. Karedok adalah makanan yang terbuat dari bahan sayuran segar dan mentah.\n\nBahan utama sayuran untuk membuatnya antara lain taoge, mentimun, kubis, kacang panjang, daun kemangi, dan terong. Sayuran yang sudah dibersihkan kemudian dicampur dengan bumbu kacang. Bumbu kacang terbuat dari cabai merah, bawang putih, kacang tanah, air asam, gula merah, garam, terasi, dan kencur yang ditumbuk.',
      photo: 'images/karedok.jpeg',
      ingredient: ' - Tauge, cuci bersih - 50 gram\n - Kacang panjang, cuci bersih dan iris kecil - 50 gram\n - Kol, cuci bersih dan iris halus - 50 gram\n - Daun kemangi, cuci bersih - 50 gram\n - Terong bulat hijau, cuci bersih dan iris tipis - 2 buah\n - Ketimun, cuci bersih dan iris kotak tipis - 1 buah\n\nBUMBU HALUS:\n - Kacang tanah, goreng - 150 gram\n - Gula merah - 50 gram\n - Bawang putih - 1 siung\n - Cabe rawit merah - 2 buah\n - Kencur - 4 cm\n - Terasi, bakar - 1/2 sdt\n - Air asam jawa - 2 sdm\n - Garam - 1 sdt\n - Air - 75 ml\n',
      procedure: '1. Dalam satu wadah besar, siapkan bumbu halus. Campur dengan air dan aduk hingga jadi pasta.\n2. Masukkan semua sayuran. Aduk hingga rata.\n3. Siap disajikan.\n'
  ),
  Food(
      name: 'Papeda',
      description: 'Papeda atau bubur sagu, merupakan makanan pokok masyarakat Maluku dan Papua. Di berbagai wilayah pesisir dan dataran rendah di Papua, sagu merupakan bahan dasar dalam berbagai makanan.\n\nSagu bakar, sagu lempeng, dan sagu bola menjadi sajian yang paling banyak dikenal di berbagai pelosok Papua, khususnya dalam tradisi kuliner masyarakat adat di Kabupaten Mappi, Asmat, hingga Mimika.\n\nPapeda terdapat di hampir semua daerah di Maluku dan Papua dan terbuat dari tepung sagu. Tepung sagu dibuat dengan cara menokok batang sagu. Papeda biasanya disantap bersama kuah kuning, yang terbuat dari ikan tongkol atau ikan mubara dan dibumbui kunyit dan jeruk nipis.',
      photo: 'images/papeda.jpeg',
      ingredient: '- Setengah kg sagu atau tepung sagu\n - 3 liter air\n - 2 buah jeruk nipis\n - 1 sdt garam\n',
      procedure: '1. Rebus air sampai mendidih. Sementara siapkan sagu dibaskom atau piring mangkok dan diberi perasan jeruk, garam, dan air dingin secukupnya. Aduk sagu cair lalu disaring.\n2. Jika air sudah mendidih siram air ke sagu yang sudah disiapkan sambil diaduk sampai masak. Tetap diaduk supaya matang merata.\n3. Papeda siap disajikan dengan sayuran dan lauk pauk.\n'
  ),
  Food(
      name: 'Sate Padang',
      description: 'Indonesia terkenal dengan sate, salah satunya sate padang yang berasal dari tanah Minangkabau. Makanan ini disajikan dalam bentuk potongan daging berukuran kecil-kecil yang sudah diolah dan dilumuri terlebih dahulu dengan bumbu rempah, ditusuk dengan tusukan bambu dan kemudian dipanggang menggunakan bara arang kayu.\n\nCiri dari sate padang ini adalah tidak ditambah kecap seperti halnya sate pada umumnya, tetapi menggunakan kuah kental yang berbahan dasar dari tepung beras. Sate padang memiliki cita rasa gurih dan pedas yang khas. Cita rasa ini akan semakin kaya dengan adanya taburan bawang goreng dan kerupuk opak.',
      photo: 'images/sate.jpeg',
      ingredient: 'DAGING:\n - Daging sapi - 500 gram\n - Daun salam - 3 lembar\n - Lengkuas, memarkan - 1 ruas\n - Air, untuk merebus - secukupnya\n\nLAINNYA:\n - Serai, memarkan lalu ikat jadi satu - 3 batang\n - Daun jeruk, sobek-sobek - 7 lembar\n - Daun kunyit, sobek-sobek - 1 lembar\n - Daun salam - 4 lembar\n - Tepung beras - 3 sdm\n - Asam kandis - 2 buah\n - Tusukan sate - secukupnya\n - Bawang merah goreng - secukupnya\n\nBUMBU HALUS:\n - Bawang putih - 50 gram\n - Bawang merah - 75 gram\n - Cabai giling halus - 3 sdm\n - Jahe - 2 ruas\n - Lengkuas - 2 ruas\n - Kunyit - 2 ruas\n - Bubuk kari - 2 sdm\n - Kayu manis - 10 cm\n - Pala - 1 butir\n - Ketumbar - 1 sdm\n - Lada - 1 sdt\n - Jinten - 1 sdt\n - Adas manis - 1 sdt\n - Bunga lawang - 2 butir\n - Kapulaga - 7 butir\n - Cengkeh - 7 butir\n\nPELENGKAP:\n - Lontong atau ketupat - secukupnya\n',
      procedure: '1. Rebus semua bahan daging hingga daging setengah empuk dan tidak berdarah lagi. Angkat dan tiriskan daging lalu potong kotak-kotak sesuai selera. Sisihkan. Simpan air rebusan daging/kaldu untuk membuat kuah. Sisihkan.\n2. Tumis bumbu halus hingga harum.\n3. Masukkan daun jeruk, daun kunyit, dan daun salam. Tumis kembali hingga benar-benar matang. Angkat dan bagi bumbu jadi 2 bagian.\n4. Ambil 1 bagian bumbu lalu campurkan dengan daging yang sudah dipotong-potong. Pindahkan dalam panci lalu tuang air secukupnya (hingga daging terendam). Masak/ungkep daging hingga empuk dan bumbu meresap. Angkat.\n5. Ambil daging lalu tusukkan dan tata di tusukan sate. Lakukan hingga habis.\n6. Panggang sate sebentar saja di atas api atau wajan datar anti lengket/teflon. Angkat.\n7. Kuah sate: Ambil 1 bagian bumbu sisanya lalu masak dengan air rebusan daging dan asam kandis hingga  mendidih.Masukkan tepung beras yang sudah dilarutkan dengan sedikit air. Aduk-aduk terus (agar tidak menggumpal) hingga kental dan meletup-letup. Koreksi rasanya. Angkat.\n8. Penyelesaian: Tata sate bersama lontong/ketupat. Siram dengan kuah sate. Beri taburan bawang merah goreng.\n9. Siap disajikan.\n'
  ),
];